# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        elixir: ['1.18.2', '1.17.3', '1.16.3', '1.15.8', '1.14.5']
        include: 
          - elixir: '1.18.2'
            otp: '27.2'
          - elixir: '1.17.3'
            otp: '27.2'
          - elixir: '1.16.3'
            otp: '26.2'
          - elixir: '1.15.8'
            otp: '25.3'
          - elixir: '1.14.5'
            otp: '25.3'
    name: Build and test
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }} # [Required] Define the Elixir version
        otp-version: ${{ matrix.otp }}      # [Required] Define the Erlang/OTP version
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.version.elixir }}-${{ matrix.version.otp }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.version.elixir }}-${{ matrix.version.otp }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile --errors-as-warnings
    - name: Run tests
      run: mix test
